export const icons = {
  back: require('./images/back_icon.png'),
  back_white: require('./images/back_icon_white.png'),
  next: require('./images/button_arrow.png'),
  user: require('./images/user_icon.png'),
  user_x: require('./images/user_icon_active.png'),
  email: require('./images/email_icon.png'),
  email_x: require('./images/email_icon_active.png'),
  lock: require('./images/password-icon.png'),
  lock_x: require('./images/password-icon_active.png'),
  // flagAu: require('./images/flags/au.png'),
  facebook: require('./images/facebook_icon.png'),
  google: require('./images/google_icon.png'),
  business: require('./images/business_icon.png'),
  business_x: require('./images/business_icon_active.png'),
  phone: require('./images/phone_number_icon.png'),
  phone_x: require('./images/phone_number_icon.png'),
  zipcode: require('./images/zip_code_icon.png'),
  zipcode_x: require('./images/zip_code_icon_active.png'),
  select: require('./images/right_arrow.png'),
  select2: require('./images/select_arrow.png'),
  map_pin: require('./images/address_icon.png'),
  map_pin_x: require('./images/address_icon_active.png'),
  tick: require('./images/date_tick.png'),
  tick_x: require('./images/date_tick_active.png'),
  tick2: require('./images/tick_icon.png'),
  add_service: require('./images/add_service_icon.png'),
  delete_service: require('./images/delete_icon-1.png'),
  edit_service: require('./images/edit_icon.png'),
  datetime: require('./images/date_time_icon.png'),
  currency: require('./images/money_icon.png'),
};
